---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install update (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: base
  name: Install Nagios in one host
  become: true
  tasks:

  - name: Install Nagios (Ubuntu) in base host
    apt:
      name:
        - nagios4
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install Nagios (Centos) in base host
    yum:
      name:
        - nagios
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: workstations
  become: true
  tasks:

  - name: Install Elastic Stack (Ubuntu) workstations
    apt:
      name:
        - elasticsearch
        - kibana
        - logstash
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install Elastic Stack (CentOS) workstations
    yum:
      name:
        - elasticsearch
        - kibana
        - logstash
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"


- hosts: db_servers
  become: true
  tasks:

  - name: Install Grafana, Prometheus, Influxdb (Ubuntu) db_servers
    apt:
      name:
        - grafana
        - prometheus
        - influxdb
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install Grafana, Prometheus, Influxdb (Centos) db_servers
    yum:
      name:
        - grafana
        - prometheus
        - influxdb
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks:

  - name: Install Lamp Stacks (Ubuntu) file_servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - mariadb-server
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install Lamp Stacks (CentOS) file_servers
    yum:
      name:
        - httpd
        - php
        - mariadb-server
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
